set nocompatible

"Once you activate this you'll need to hold shift to use text selection to/from
"outside vim.
set mouse=a

set autoread

syntax on

set number
set relativenumber

set tw=80

colorscheme molokai

filetype plugin indent on
set expandtab
set tabstop=8
set softtabstop=2
set shiftwidth=2
set smarttab
set backspace=indent,eol,start

" Removes spaces at end of lines when writing
autocmd BufWritePre *.c,*.h,*.cpp,*.cxx,*.cc,*.hh,*.hxx :%s/\s\+$//ge

" Closes Brackets, braces, strings... automatically
autocmd FileType php,c,java,cpp,js inoremap /* /*  */<Esc>hhha
autocmd FileType c,cpp,sh inoremap ( ()<Esc>i
autocmd FileType c,cpp,sh inoremap { {<CR>}<Esc>ko
autocmd FileType c,cpp inoremap [ []<Esc>i

set pastetoggle=<F10>

set splitbelow
set splitright
